### ISSUE TITLE
Some datasets are showing twice on the home page.

### ISSUE THREAD

**Issue by Eric4Jiang** [cvfadmin/COVE#35] opened 2019-07-08 06:00 UTC
For example, if you keep scrolling, you eventually see "Music Video Dataset", "Makeup in the Wild", "Actor and Action Dataset" twice.

If I search for them though, they only appear once.

**Comment by ddehueck** [comment] 2019-10-07 15:44
@Eric4Jiang Did you ever identify the cause for this bug? Or the ability to replicate consistently?

**Comment by Eric4Jiang** [comment] 2019-10-07 15:44
Still shows up

**Comment by ddehueck** [comment] 2020-01-16 07:23
Closing until we can replicate and find it the same bug after #56

**Closed by ddehueck** 2020-01-16 07:23 UTC
Labels: bug, can't replicate
